name: Push to Readymage
on:
  push:
    branches: main

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        shell: bash
        run: |
          git config --global user.email "Satoshi@bot.com"
          git config --global user.name "Satoshi bot"

      - name: Pulling from this repo
        shell: bash
        run: |
          git clone https://github.com/SH1R3F/Test-GH-Actions-X.git
          cd Test-GH-Actions-X
          rm -rf .github/workflows/

      - name: Push to the other repo
        shell: bash
        run: |
          git remote remove origin
          git remote add origin https://SH1R3F:${{ secrets.PAT_TOKEN }}@github.com/SH1R3F/Test-GH-Actions-Y.git
          git add .
          git commit -m ${{ github.event.head_commit.message }}
          git push -u origin main -f
