name: attmpt 123
on: push
permissions:
  contents: write
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling from other repo
        shell: bash
        run: |
          date > generated1.txt
          git config --global user.email "Bot@example.com"
          git config --global user.name "Bot"
          git config --global url.https://${{ secrets.PAT_TOKEN }}@github.com/
          git clone https://github.com/SH1R3F/Test-GH-Actions-Y.git
          cd Test-GH-Actions-Y
          date > generated2.txt
          git remote remove origin
          git remote add origin https://SH1R3F:${{ secrets.PAT_TOKEN }}@github.com/SH1R3F/Test-GH-Actions-X.git
          git remote set-url origin https://SH1R3F:${{ secrets.PAT_TOKEN }}@github.com/SH1R3F/Test-GH-Actions-X.git
          git add .
          git commit -m "test"
          git push -u origin main -f
