name: Update Helm Manifests
on: push
permissions:
  contents: write
jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "src"
          ref: "main"
          persist-credentials: false

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "dest"
          ref: "main"
          repository: "SH1R3F/Test-GH-Actions-Y"
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      - name: Copy common files to new repo
        shell: bash
        run: |
          mkdir -p dest/
          cp -rvT src/ dest

      - name: Push
        shell: bash
        run: |
          git init
          git remote add origin "https://SH1R3F:$token@github.com/SH1R3F/Test-GH-Actions-Y"
          git config --global user.name "bot X"
          git config --global user.email "bot-X@test.com"
          git commit -m "hmmm"
          git push
