name: Example Push Action
on: push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: QXIP/github-action-push-to-another-repository@v1.4.2

        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }}
        with:
          source-directory: "output"
          destination-github-username: "SH1R3F"
          destination-repository-name: "Test-GH-Actions-Y"
          user-email: carles3@pina.cat
          target-branch: main
