name: Example Push Action
on: push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/SH1R3F/Test-GH-Actions-Y
          git commit -m "generated"
          git push
