name: Sync to Repository Y

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository X
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set up Git
        run: |
          git config --global user.name 'Satoshi'
          git config --global user.email 'Satoshi@scandiweb.com'

      - name: Push to Repository Y
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote add target https://$PAT_TOKEN@github.com/SH1R3F/Test-GH-Actions-Y.git
          git push target main --force
