- name: Generate API module
  env:
    PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  run: |
    git config --global user.name 'github-actions[bot]'
    git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    git config --unset-all http.https://github.com/.extraheader
    git remote add target https://$PAT_TOKEN@github.com/SH1R3F/Test-GH-Actions-Y
    git push target main --force
