name: update multi repos

on:
  push:
    branches:
      - "main"

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "src"
          ref: "main"
          persist-credentials: false

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "dest"
          ref: "main"
          repository: ""
          token: ${{secrets.PAT_TOKEN}}
          persist-credentials: false

      - name: Copy files
        shell: bash
        run: |
          mkdir -p dest
          cp -rvT src/

      - name: push them
        run: |
          git config --global user.name "test"
          git config --global user.email "test@test.com"
          git commit -m "test"
          git push
