name: update multi repos

on:
  push:
    branches:
      - "main"

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to Repository
        uses: SH1R3F/Test-GH-Actions-Y
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }}
        with:
          user-name: "github-actions[bot]"
          user-email: github-actions[bot]@users.noreply.github.com
          source-directory: "output-dir"
          destination-github-username: "username"
          destination-repository-name: "repo-name"
          target-branch: main
