name: attmpt 123
on: push
permissions:
  contents: write
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling from other repo
        shell: bash
        run: |
          git config --global user.email "Satoshi@bot.com"
          git config --global user.name "Satoshi bot"
          git clone https://github.com/SH1R3F/Test-GH-Actions-X.git
          cd Test-GH-Actions-X
          date > generated3.txt
          rm -rf .github/workflows/
          git remote remove origin
          git remote add origin https://SH1R3F:${{ secrets.PAT_TOKEN }}@github.com/SH1R3F/Test-GH-Actions-Y.git
          git remote set-url origin https://SH1R3F:${{ secrets.PAT_TOKEN }}@github.com/SH1R3F/Test-GH-Actions-Y.git
          git add .
          git commit -m ${{ github.event.head_commit.message }}
          git push -u origin main -f
